baseURL: "https://bhumik98.github.io"
languageCode: "en-us"
title: "Bhumik"
theme: master

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  #title: "Hugo Profile"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # dark
    color:  
        secondaryBackgroundColor: "Blue"
    #darkmode:
        #secondaryBackgroundColor: "Blue"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #     textColor: "black"
  #     secondaryTextColor: 
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
      position: absolute
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi there! I'm "
    title: "Bhumik Shah"
    #subtitle: 
    content: "A passionate Data Analyst who loves using data to build stories and enhance products. I'm also a foodie and an avid Trekker ! I live in New Jersey, NJ. 
    My motto #every data has a story to tell"
    image: images/IMG-5460.jpg
    button:
      background - color: 
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/164f9JTSkXaly6gqoAQZk3IqH4Nul6J2i/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/bhumik98
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/bhumik98/
      #customIcons:
        #- icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "I'm Open to work"
    image: /images/IMG-1334.jpg 
    content: |-
     Currently searching for full time opportunities 
     A Masters in Information Systems graduate with 3+ years of experience in SQL, Python, R, Big Data Tableau and Power BI . 
     I have a strong interest in the the intersection of Technology and Business. I am a certified AWS Cloud Practioner and a certified Tableau Dekstop Specialist
     
    skills:
      enable: true
      title: "Skills:"
      items:
        - "Python, R, SQL, Spark in Databricks, Data Visulaization , AWS"
        - "Mentorship, Multi-Cultural Fluency, Team Player"
       

  # Experience
  experience:
    enable: true
    items:      
      - job: "Data Analyst"
        company: "Synchrony Financial"
        companyUrl: "https://example.com"
        date: "Aug 2022 - Jul 2023"
        info:
          enable: true
          content: "Location: Remote "
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |-
          Remote
          - Involved in complete Agile/SDLC Requirement Analysis, System, and Integration Testing of the Consumer Insights Division.
          - Involved using tools like MS Excel, SQL, programming languages such as Python to perform A/B Testing, calculations, generate visualizations, and conduct exploratory data analysis.
          - Developing models, algorithms, orstatistical approaches to solve specific business problems or answer research questions.
          - Create and publish multiple dashboards and reports using the Tableau server.
          - Involving writing, testing, and implementing triggers, stored procedures, and functions at the Database level using MySQL

      
      - job: "Teaching Assitant - Data Analytics and Machine Learning"
        company: "Stevens Institute of Technology"
        companyUrl: "https://www.stevens.edu/"
        date: "Jul 2022 - May 2023"
        info:
          enable: true
          content: "Location: Hoboken, NJ"
        featuredLink:
          enable: false
          url: "https://www.stevens.edu/"
        info:
          content:
        content: |-
          Hoboken , NJ
          - Mentored 80+ students on Python and Data Analytics for graduate course MIS 637 Data Analytics and Machine Learning
          - Conducted weekly doubt-solving sessions  tools like: Pandas, Seaborn, PySpark, Sci-kit Learn, other responsibilities included grading Python assignments, reviewing student projects.

      - job: "Research Assitant "
        company: "Stevens Institute of Technology"
        companyUrl: "https://www.stevens.edu/"
        date: "May 2022 - Jul 2022"
        info:
          enable: true
          content: "Location: Hoboken, NJ"
        featuredLink:
          enable: false
          url: "https://www.stevens.edu/"
        info:
          content:
        content: |-
          Hoboken , NJ
          - Created a solution for cutting-stocks problem to maximize metal sheet utilization, optimized algorithm, and integrated Gurobi Optimizer tool resulting in 65% performance boost. Improved version efficiently manages large stock sheets with minimal waste.
          
      - job: "Data Analyst"
        company: " Jim Solutions"
        companyUrl: "http://www.jimsolution.com/"
        date: "May 2019 - Jun 2021"
        info:
          enable: true
          content: "Location: Mumbai, India "
        featuredLink:
          enable: false
          url: "http://www.jimsolution.com"
        content: |-
          Mumbai, India
          - Assisted in performing exploratory data analysis to identify patterns, trends, and insights, providing data reporting infrastructure.
          - Ensured data quality and integrity by implementing data validation checks, monitoring data accuracy and consistency, and maintaining data documentation and standards.
          - Optimized SQL queries for performance and scalability, improved database performance by 20% and loading speed by 10%.
          - Developed models, algorithms, or statistical approaches to solve specific business problems or answer research questions.
          - Responsible for test cases, test scenarios, unit & system testing, system integration, conducting User Acceptance Testing (UAT)


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Masters in Information Systems (Data Concentration)"
        school:
          name: "Stevens Institute of Technology, New Jersey"
          url: "https://www.stevens.edu/"
        date: "2021 - 2023"
        GPA: "3.9 out of 4.0"
        content: |-
            - Was a Teaching Assistant for Data Analytics and Machine Learning at the Stevens School of Business , Stevens Institute of Technology
            - Worked as a Research assistant to craete cutting-stocks problem to maximize metal sheet utilization
            - Attending Grace Hopper 2022 Conference with University Scholarship
            - Course Work: Big Data Analytics, Data Analytics and Machine Learning, Marketing Analytics, Project Management , Applied Analytics .

            Extracurricular Activities
             - Conducted and Mentored a Tableau workshop under Stevens Indian Association
             - Active member of Stevens Photography club
      - title: "Bachelor of Engineering in Computer Science and Engineering (Hons.)"
        school:
          name: "University Of Mumbai, Mumbai"
          url: "http://www.iiitkottayam.ac.in/#!/home"
        date: "2017 - 2020"
        content: |- 
          - Data Science Courses: Artificial Intelligence, Data Warehousing and  Data Mining, Big Data Analytics, Predictive Analytics, Database Management, 
          - Computer Science Courses: Cloud Computing, Cryptography and Network Security, Computer Programming, Data Structures, Computer Networks, Computer Organization, Compiler Design, Block Chain Technology, IoT (Internet of Things), Operating Systems, Soft Computing, Distributed and Parallel Computing, High Performance Computing, Theory of Computation, Object Oriented Analysis and Design,
          - Software Management Courses: Software Engineering and Project Management, Software Design Patterns
          - Other Courses: Personality Development, Communication Skills, Economics, Human Resource Management, Operation and Supply Chain Management
          
          
          Extracurricular Activities
            - Was the Elected Cultural Club Secretary from 2019-2021
            - Won several Photography competitions throughout.

  #featuredLink:
  #enable: true
  #name: "My academic record"
  #url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      #- title: Smart India Hackathon 2020
       # content: Won 2nd place in Smart India Hackathon 2020 for developing a Smart Yoga Instructor with feedback using Deep Learning
        #url: "https://www.sih.gov.in"
      - title: Published paper on IOT based soil moisture irrigation and farming system
        content: Created a project using multiple sensors and IoT to gather and exchange information that can either be monitored real-time or logged for further use. Hence, irrigation may not only reduce the manual labor of farmers but also help in saving water by controlling the usage..
        url: "https://www.ijtsrd.com/engineering/computer-engineering/30968/iot-based-autonomous-irrigation-system/omkar-sadwilkar"
      - title: Event Manager at Comic-Con India
        content: Worked as a team lead handle a team of 20 to help Cosplay registration and media personnel and handling a large crowd of 5000+ people at the largest comic event in India
      - title: Animal rescue activist 
        content: Working as an Animal rescue activist for a many years both on and off site helping on ground rescues and virtual donation drives. Collabrated with multiple organizations and people Pan India to protect and increase animal welfare and provide back to community.

      - title: Certified AWS Cloud Practioner
        content: To gain insights and knowledge of cloud products and services of Amazon AWS and use ithem in professional and academic career.
        url: "https://www.credly.com/badges/08da55af-7d81-459e-9b8d-6202e4b15377/linked_in_profile"

      - title: Certified Tableau Desktop Specialist
        content: To create amazing and easy to understand data visualuzation and help understand data and present to stakeholder
        url: "https://www.credly.com/badges/d3ffa58b-e7b8-499b-ab8f-3d5dcab38de7/linked_in_profile"


  # projects
  projects:
    enable: true
    items:

      - title: Churn rate detection case study using AWS , Snowflake , Tableau/Power BI
        content: Solved a Case study for a fictional telecom company Databel to detect the churn rate and churn reasons ranging the geographic location and other factors increasing the churn rate .
        image: images/projects/advert12.jpeg
        featured:
          name: Click here to know more!
          link: https://docs.google.com/presentation/d/1BqEMqAD-FUo2e7IvXX7SgG8yitriOEpN/edit?usp=sharing&ouid=115942155030052699279&rtpof=true&sd=true
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/bhumik98/Churn-Rate-predict

      - title: Youtube Data Analysis
        content: An analysis on structured and semi-structured YouTube videos data based on the video categories and the trending metrics
        image: /images/projects/Colorization34.png
        featured:
          name: Click here to know more!
          link: https://docs.google.com/presentation/d/193X-n0sXoFbMR9dD7rxJxwM8n_GpOwNQ/edit?usp=sharing&ouid=116008293600462184270&rtpof=true&sd=true
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/bhumik98/Youtube-Data-analysis-using-aws
          # - icon: fab fa-twitter
          #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Euro satellite Image Classification using CNN
        content: classified 16000 satellite images of Europe from kaggle and build a model to detect images using CNN algorithm .
        image: /images/projects/doge45.jpg
        featured:
          name: Click here to know more!
          link: https://github.com/bhumik98/EUROSATCNN
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/bhumik98/EUROSATCNN/blob/main/RIDSABSOLUT.ipynb


  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: bhumik1998@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/bhumik98
      linkedin: https://www.linkedin.com/in/bhumik98/
    # twitter: https://twitter.com
      #instagram: https://www.instagram.com/keerthi__sreenivas/
    # facebook: https://facebook.com
